"""back

Revision ID: daf514c5362e
Revises: 21af17fa7463
Create Date: 2016-10-10 18:09:51.689785

"""

# revision identifiers, used by Alembic.
revision = 'daf514c5362e'
down_revision = '21af17fa7463'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'send_loc')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('send_loc', sa.VARCHAR(), nullable=True))
    ### end Alembic commands ###
